### ISSUE TITLE
System.InvalidCastException on MultiUrlPickerValueConnector

### ISSUE THREAD

**Issue by rlynggaard** [umbraco/Umbraco.Deploy.ValueConnectors#1]
When trying to deploy to cloud, when we're using RJP.MultiUrlPicker which is set to only on link an error is thrown. It seems like RJP..MultiUrlPicker no longer returns an array of links, if the editor only can select one link - it then returns an object of type Link
`ERROR Umbraco.Deploy.Work.WorkEnvironment - Deployment failed.
System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Deploy.ValueConnectors.MultiUrlPickerValueConnector.GetValue(Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.GridCellValueConnectors.LeBlenderGridCellValueConnector.GetValue(GridControl control, Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.ValueConnectors.GridValueConnector.GetValue(Property property, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.<>c__DisplayClass7_0.<MapProperties>b__1(Property x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Umbraco.Deploy.ServiceConnectors.ContentConnectorBase`2.MapProperties(PropertyCollection properties, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.MapVersion(IContent content, ICollection`1 dependencies)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi, IContent content)
   at Umbraco.Deploy.ServiceConnectors.DocumentConnector.GetArtifact(GuidUdi udi)
   at Umbraco.Deploy.ServiceConnectors.ServiceConnectorBase`3.Umbraco.Core.Deploy.IServiceConnector.GetArtifact(Udi udi)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.<GetArtifacts>b__16_0(Udi x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.CreatePackage(Guid sessionId, Manifest manifest)
   at Umbraco.Deploy.Environments.LocalUmbracoEnvironment.CreatePackageAsync(Guid sessionId, Manifest manifest, CancellationToken token)
   at Umbraco.Deploy.WorkItems.DeployRestoreWorkItemBase.<CreatePackageOnSource>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---`

**Comment by hfloyd** [comment]
I noticed the same issue.

**Comment by clausjensen** [comment]
Please register this as an issue at http://issues.umbraco.org/ - otherwise it most likely will not get prioritized any time soon. This repository is purely for example code of the internal connectors done in Deploy. 🙈 

Will get the issue feature of this repository closed asap - sorry about that!

**Comment by hfloyd** [comment]
@clausjensen - Thanks for the info. Three questions for you:
1. Should "deploy" related issues be added to the "Courier" area (http://issues.umbraco.org/issues/COU), or to the Umbraco Cloud one (http://issues.umbraco.org/issues/UAAS) or will there be a new "Deploy" area added to the Issues site?

2. Are there any plans for something similar to https://github.com/umbraco/Umbraco.Courier.Contrib for these new Deploy ValueConnectors? Is it safe to assume that you are providing these examples because developers can create their own ValueConnectors to install into a site to handle custom DataTypes, etc?

3. Regarding this specific bug... For myself, and possibly for others (such as the OP @rlynggaard), this causes a serious "breaking change" in existing sites which have been upgraded to 7.6 + Deploy. Is it possible to create a "fixed" copy of this ValueConnector - either via a PR to Deploy, or by just dropping a new ValueConnector into a site? If the latter, is there some way to "override" the original version which is included with Deploy?

**Comment by hfloyd** [comment]
I found the answer to #2... https://github.com/umbraco/Umbraco.Deploy.Contrib
